- internal/llm/provider/anthropic.go
- internal/llm/tools/view.go
- internal/tui/exp/list/filterable.go
- internal/tui/exp/list/filterable_group.go
> perf: avoid regex compilation in runtime

- internal/config/config.go
- internal/llm/agent/agent.go
- internal/llm/provider/openai.go
> Fix some openrouter models

- internal/cmd/root.go
> fix: panic in non-interactive mode when no providers set up

- .goreleaser.yml
- go.sum
so users can install from source as well.
https://aur.archlinux.org/packages/crush
> ci: aur sources

- internal/tui/components/chat/editor/editor.go
closes #397
I couldn't reproduce the original issue, but it seems to be in this line.
> fix: nil pointer in view

- internal/tui/page/chat/chat.go
- internal/tui/tui.go
> fix: handle code agent not initialized

- internal/llm/agent/mcp-tools.go
judging by the error an user reported on slack, it seems we need to call mcpclient.start too.
from the godocs:
```golang
// Start initiates the connection to the server.
// Must be called before using the client.
```
> fix: mcp client must be started

- internal/app/app.go
- internal/app/lsp.go
- internal/app/lsp_events.go
- internal/llm/agent/mcp-tools.go
- internal/lsp/client.go
- internal/lsp/handlers.go
- internal/tui/components/chat/sidebar/sidebar.go
- internal/tui/components/chat/splash/splash.go
- internal/tui/components/files/files.go
- internal/tui/components/lsp/lsp.go
- internal/tui/components/mcp/mcp.go
This will show the correct state for MCPs and LSPs so the users know if there is an issue with their config
https://github.com/user-attachments/assets/e0e74fa4-aa3b-4759-9a3a-937756c85321
> fix: correctly show mcp and lsp states

- internal/cmd/update.go
- internal/version/version.go
using the spinner, and adding a timeout.
> fix: small improvements on auto-updater

- internal/llm/agent/agent.go
This fixes the summarize model so that it uses the large model instead of the small one. This fixes a bug where the small model had a smaller context size than the large model.
> fix: summarize provider should be large

- README.md
> docs: add scoop

- internal/config/config.go
- schema.json
> fix: add $schema to jsonschema

- internal/permission/permission.go
- internal/tui/components/chat/editor/editor.go
- internal/tui/components/dialogs/commands/commands.go
- internal/tui/page/chat/chat.go
- internal/tui/styles/charmtone.go
- internal/tui/styles/theme.go
- internal/tui/tui.go
This adds the yolo mode to the commands and shows a warning.
https://github.com/user-attachments/assets/860f6c6f-c5b9-4b22-b09a-fcbdfe6775a8
> feat: add yolo mode command

- internal/llm/agent/mcp-tools.go
Fixes regression with broken pipes for stdio mcps
> fixup stdio mcp startups to match mark3labs upgrade

- internal/tui/components/chat/chat.go
Makes the queue push the messages above so it shows correctly
Before:
After:
> fix: make the queue push the messages above

- internal/llm/agent/mcp-tools.go
> fix(mcp): tool output join with new line

- internal/config/config.go
- internal/llm/agent/mcp-tools.go
- schema.json
closes #604
closes https://github.com/charmbracelet/crush/discussions/754
> feat(mcp): configurable MCP timeout

- internal/config/load.go
- internal/fsext/home.go
- internal/fsext/ls.go
- internal/fsext/owner_others.go
- internal/fsext/owner_windows.go
- internal/fsext/parent.go
- internal/tui/components/dialogs/models/apikey.go
* Ref: https://github.com/charmbracelet/crush/issues/254
Consider this a proposal. Add your thoughts. Also, give it a try to check that it's really working as expected for you.
> feat: if a `.crush` directory is present in a parent dir, use that

- internal/config/provider.go
adds some more info to the cache logs so its easier to debug issues.
refs #793
> fix: improve provider cache logs

- internal/app/app.go
We need to track the number of read bytes per message.
Fixes #871
Fixes #848
> fix: fix `panic` that happens on `crush run` with tool calls

- internal/tui/components/chat/splash/splash.go
* Closes https://github.com/charmbracelet/crush/issues/795
<details><summary>Before</summary>
<p>
</p>
</details>
<details><summary>After - Grey version</summary>
<p>
</p>
</details>
<details><summary>After - Green version</summary>
<p>
</p>
</details>
> feat: show path when asking if the user wants to initialize project

- internal/llm/provider/openai.go
> Fix openai provider tool calls

- internal/app/app.go
- internal/db/connect.go
- internal/llm/agent/mcp-tools.go
I have stumbled upon great article https://antonz.org/sqlite-secure-delete/ and realized that crush's underlying SQLite database can contain many sensitive information. It would be better to set stricter rules for session data deletion.
> security(sqlite): enable `secure_delete` pragma

- go.mod
- go.sum
- internal/lsp/watcher/global_watcher.go
- internal/lsp/watcher/global_watcher_test.go
Add ignore support for lsp watcher
> Lsp watcher ignore

- internal/llm/provider/gemini.go
Fix for https://github.com/charmbracelet/crush/issues/878
> Please ensure that the number of function response parts is equal to the number of function call parts of the function call turn.
Crush constructed tool responses with the wrong role
Also includes the tool responses patch from the linked issue
> Fix Gemini tool responses getting constructed incorrectly 

- README.md
added some docs for https://github.com/charmbracelet/nur/pull/20
> docs: add bit about nixos module

- internal/llm/agent/mcp-tools.go
it was asking for the tools, if it errors, it was setting state to error, but was then overwriting it right away with status success.
> fix(mcp): do not eat list tools errors

- internal/tui/components/dialogs/models/keys.go
Minor changes to language in model chooser help.
💘 Generated with Crush
> chore: update model chooser key help text

- internal/cmd/dirs.go
- internal/cmd/logs.go
- internal/cmd/root.go
- internal/cmd/schema.go
- internal/config/load.go
adds a 'dirs' command to print the config and data directory.
> feat: crush dirs

- Taskfile.yaml
Small one to assure tags are annotated during release.
> chore(task): annotate tags during release

- Taskfile.yaml
Super tiny. I'm fine closing if this is just bloat too.
> chore(task): add helper for fetching tags
