- internal/tui/tui.go
This prevents a broken state when the model is busy
> chore: prevent switching the model while agent is working

- internal/config/load.go
- internal/llm/provider/anthropic.go
This was a bug that prevented custom headers to be added to anthropic providers
> chore: fix custom headers and system prefix

- internal/tui/components/chat/splash/splash.go
* Fixes https://github.com/charmbracelet/crush/issues/381
* Fixes https://github.com/charmbracelet/crush/issues/389
* Fixes https://github.com/charmbracelet/crush/issues/401
A bug on onboarding made it impossible to press "y" and "n" on onboarding, on both the model list and the API key field.
This also means that on some terminals, like the Windows Terminal, pasting an API key would supress all "y" and "n" chars present in the key, because these terminal receives an even for each character being pressed.
To reproduce:
* Run `rm -r ~/.local/share/crush` to delete config
* Run Crush to show onboarding
* Try to press <kbd>y</kbd> and <kbd>n</kbd> on model list and API key field
> fix(onboarding): fix y/n key press on model list and api key field

- internal/config/config.go
data that is stored in plain text (api keys, etc.)
closes #411
Simple change to default permissions of crush.json file. 
See Issue #411
> Use default permissions of 0600 for crush.json

- internal/llm/tools/tools.go
Should fix #375.
***
Editor’s note:
This limits the amount of tokens a tool call can use, avoiding cases where one line in a file is long enough that it could consume all of the available context. This adds a width and height limits on to messages and generally enforces a character limit.
> chore: limit tool output

- internal/config/load.go
- internal/csync/maps.go
- internal/csync/maps_test.go
- internal/fsext/ignore_test.go
- internal/fsext/ls.go
- internal/tui/components/chat/editor/editor.go
git checks, in order:
- ./.gitignore, ../.gitignore, etc, until repo root
- ~/.config/git/ignore
- ~/.gitignore
This check the following:
- the given ignorePatterns
- crush's commonIgnorePatterns
- ./.gitignore, ../.gitignore, etc, until dl.rootPath
- ./.crushignore, ../.crushignore, etc, until dl.rootPath
- ~/.config/git/ignore
- ~/.gitignore
- ~/.config/crush/ignore
> feat: improve gitignore and crushignore support

- internal/llm/tools/tools.go
This may cause more problems than it fixes, as for instance, it cuts json responses as well, rendering them invalid.
> fix(tools): do not truncate output

- internal/llm/agent/agent.go
- internal/llm/agent/mcp-tools.go
If a MCP gets stuck starting/connecting, chatting will not work.
This makes it so it'll timeout after 5s (we can discuss the time), and then everything works accordingly.
> fix(mcp): give a time limit for startup

- internal/llm/provider/gemini.go
fix #467
Previously, Gemini API would silently terminate when reaching its rate limit.
Before|After
-|-
> fix(gemini): retry at rate limit

- internal/fsext/fileutil.go
- internal/llm/tools/edit.go
- internal/llm/tools/multiedit.go
- internal/tui/components/chat/sidebar/sidebar.go
- internal/tui/components/files/files.go
* Closes #684
---
* `fix(tool): fix edit and multi-edit tools on windows`
We should convert the content to LF to apply the patch while still
respecting the original line endings when saving the file on disk.
* `fix(sidebar): compute the right line count even on windows / crlf`
The diff library we're using assumes LF, so we need to convert CRLF to LF to ensure it works properly.
In the screenshots below, in both cases we had only 1 line removed and 3 added, but it was as if the whole files was changed before the fix.
<details><summary>Before</summary>
<p>
</p>
</details> 
<details><summary>After</summary>
<p>
</p>
</details> 
* `fix(sidebar): fix full path appearing on sidebar on windows`
For some reason, this was only happening for OpenAI on Windows, and not for Anthropic. …
> fix: fix three important bugs on windows

- internal/tui/components/chat/editor/editor.go
Basically, show shorter paths first.
Before:
Now:
> fix(editor): better sorting of files when completing with /

- internal/llm/provider/anthropic.go
- internal/llm/provider/openai.go
If the server is down, address don't resolve, or another myriad of reasons, currently, it'll get stuck.
This makes it so it times out after 1 minute.
> fix(llm): set request timeout

- internal/llm/tools/diagnostics.go
- internal/lsp/client.go
Return a copy of lsp diagnostics in `GetDiagnostics` to avoid data race.
Previously, the internal map is returned directly. Other goroutines can read it without lock.
- closes https://github.com/charmbracelet/crush/issues/676
> fix(lsp): return a copy of lsp diagnostics to avoid data race

- internal/llm/provider/gemini.go
The issue was apparently that the go-genai module expects the roles in the chat history to be [either "user" or "model"](https://github.com/googleapis/go-genai/blob/main/chats.go#L93). Since the tool calls in the history were assigned the role "function", combined with the fact that the [chat creation errors were being ignored](https://github.com/charmbracelet/crush/blob/main/internal/llm/provider/gemini.go#L200), resulted in this cryptic/weird issue. This pr introduces a workaround by attributing the tool-call's output to the model.
Steps to validate the fix:
- make the llm perform any tool call.
- the main branch panics, while this branch does not.
PS: I'm not sure if this is a "proper fix", since the tool call results shouldn't most likely be attributed to the model in the history.
> fix(gemini): tool-calling panic issue

- internal/fsext/ls.go
- internal/fsext/ls_test.go
Fixed critical bug where gitignore patterns like .* would match the root directory itself, causing filepath.SkipDir to abort entire file listing. The fix prevents gitignore rules from applying to the scan root directory, matching Git's actual behavior.
Also fixed typos in debug log messages (ingoring -> ignoring).
> fix(fsext): prevent .* gitignore from ignoring entire root dir

- internal/cmd/root.go
- internal/db/connect.go
- internal/llm/prompt/init.md
This is a simple quality of life ™️ improvement:
* We won't be asking the LLM to update the project's `.gitignore` anymore
* We're automatically creating a `.crush/.gitignore` file with `*` to just ignore everything inside `.crush`
* We're creating that file as soon as we create the `.crush` directory
* Before, since we were asking the LLM the update `.gitignore`, if the user chose NOT to initialize the repo, we were not ignoring `.crush` automatically at all (requiring the user to manually update `.gitignore`)
---
* Closes #588
* Closes #254
* Follow-up of #25
> feat: create `.crush/.gitignore` automatically

- internal/tui/components/dialogs/models/models.go
- internal/tui/exp/list/filterable_group.go
Tiny bugfix - this just propagates the 'placeholder' text through to the bubbles textinput when it changes in the filterableGroupList component.
This fixes a small bug where the model selector has the same label in the large and small model choice.
Also replaces a hardcoded placeholder string for the matching constant.
https://github.com/user-attachments/assets/31dcc151-5a65-450d-a070-ff629cb7fe32
> fix(tui): fix model filter placeholder text

- README.md
- internal/config/config.go
- internal/lsp/client.go
- schema.json
This PR introduces new config field `lsp.[].env` which allows user to pass custom environment variables to registered LSP.
Example:
```json
{
"lsp": {
"Go": {
"command": "gopls",
"env": [
"GOTOOLCHAIN=go1.24.5"
]
}
}
}
```
> feat(lsp): Pass custom environment variables to LSP via config

- internal/llm/tools/bash.go
While going through the code, noticed that we are using the same log when `sessionID` and `messageID` are empty in edit.go and bash.go. A simple CR to update the log.
> (minor) Update log msg for bash tool

- internal/tui/page/chat/chat.go
* Closes https://github.com/charmbracelet/crush/issues/812
* Follow-up of https://github.com/charmbracelet/crush/pull/817
To reproduce:
* `rm -rf ~/.config/crush; rm -rf ~/.local/share/crush`
* Open `crush` on onboarding
* Notice how you can navigate using arrows, filter, etc
* Click on the screen
* Not the onboarding screen will stop processing events properly (can't navigate, filter, choose model, etc)
> fix(onboarding): fix onboarding screen "freezing" when on click on it

- go.mod
- go.sum
With this, Windows users can now simply paste into Crush and bracketed paste mode along with win32 input mode will just work converting escape sequences and Windows API input events into proper events and decoding them to UTF-8 and processing them correctly for paste.
> chore: bump bubbletea and ultraviolet to support win32 input mode

- internal/llm/provider/anthropic.go
The anthropic.MessageNewParams uses omitzero tag, but an empty slice is not considered zero value. Return nil instead of empty slice when no tools are provided to ensure proper omitzero behavior.
This causes issues with Anthropic-compatible APIs (DeepSeek V3.1) that reject empty tools arrays. The current implementation returns an empty slice [] for tools when none are provided, but APIs expect the field to be omitted entirely when no tools are available.
```plain
{"time":"2025-08-22T16:20:39.19702+08:00","level":"DEBUG","source":{"function":"github.com/charmbracelet/crush/internal/log.(*HTTPRoundTripLogger).RoundTrip","file":"github.com/charmbracelet/crush/internal/log/http.go","line":46},"msg":"HTTP Request","method":"POST","url":{"Scheme":"https","Opaque":"","User":null,"Host":"api.deeps …
```
> fix: return nil for empty tools slice to handle omitzero properly

- internal/llm/agent/mcp-tools.go
This PR fixes a nil pointer dereference that occurs when MCP tools have no input schema properties defined. When using OpenAI-Compatible APIs like DeepSeek, the API expects function parameters to be a valid object schema, but was receiving null when MCP tools had no parameters, causing a 400 Bad Request error: `Invalid schema for function 'mcp_nvim_get_targets': null is not of type "object"`.
The fix ensures that the parameters field is always initialized to an empty map {} when b.tool.InputSchema.Properties is nil, satisfying the OpenAI function calling schema requirements.
> fix: prevent nil pointer dereference in mcp tools parameters

- internal/llm/provider/anthropic.go
Allow the user to specify customized bedrock host. This is supported by Claude Code env variable `ANTHROPIC_BED_ROCKBASE_URL`.
No, as this is quite straightforward. But if you need, I can do that.
> feat: support Anthropic base url option

- .github/dependabot.yml
This is proposal. See main PR on `meta`:
* https://github.com/charmbracelet/meta/pull/235
Opened here because we disabled the Dependabot config sync for this repository.
> chore: group dependabot updates to reduce noise

- internal/llm/provider/anthropic.go
- internal/llm/provider/gemini.go
- internal/llm/provider/openai.go
Fix invalid assistant messages after an interrupted tool call.
- OpenAI path:
- Only serialize finished tool calls (`ToolCall.Finished == true`) in assistant messages.
- Skip appending empty assistant messages (no `content` and no finished `tool_calls`)
- Anthropic path:
- Only emit tool_use blocks for finished calls. 
- Gemini/Vertex path:
- Only emit function calls for finished calls. 
How to test:
- Start a tool call (e.g., ask the agent to grep), interrupt with Ctrl+C
mid-run, then send a new prompt.
- Before: OpenAI-style providers returned a 400 for invalid assistant
message.
- After: Request proceeds without error; conversation continues
normally.
Fixes #920 
comment:
> fix: tool calls break the conversation if interrupted

- internal/llm/agent/agent.go
- internal/llm/provider/gemini.go
Fixes #975
***
**Editor's note:** this essentially fixes an issue where Gemini could loop uncontrollably when attempting to generate titles (it was responding with `200 OK` but with a content length of zero, which was resulting in a loop above the exponential backoff logic).
> Handle no content for gemini provider

- go.mod
- go.sum
- internal/lsp/watcher/global_watcher.go
- internal/lsp/watcher/global_watcher_test.go
Fixes too many open files issue
Before: Non-recursive watching - You must manually add each directory to watch and it creates thousands of file descriptors (one per directory). Leading tsystem limit to open files.
After: Recursive watching but single point uses FSEvents directly (as fsnotify but in this case it does at one shot), inotify (same thing of macos) and ReadDirectoryChangesW (it's mostly likely to be same as fsnotify)
```go
// befOre
err := fsext.WalkDirectories(root, func(path string, d os.DirEntry, err error) error {
gw.addDirectoryToWatcher(path)  // Opens a file descriptor
})
// after
watchPath := filepath.Join(root, "...")
notify.Watch(watchPath, gw.events, events)  // 1 watch for entire tree
```
> feat: fix too many open files issue

- README.md
* Closes #1064
Asking a review mostly to get opinions on what to link. Our projects usually link [`/contribute`](https://github.com/charmbracelet/crush/contribute), but it doesn't show the content directly, which is a bit odd. We could link the [`CONTRIBUTING.md`](https://github.com/charmbracelet/.github/blob/main/CONTRIBUTING.md) file directly, but for now I linked [the Contribute tab on the repo homepage](https://github.com/charmbracelet/crush?tab=contributing-ov-file).
> docs(readme): mention contributing guide

- internal/llm/tools/bash.go
- internal/llm/tools/bash.md
- internal/llm/tools/diagnostics.go
- internal/llm/tools/diagnostics.md
- internal/llm/tools/download.go
- internal/llm/tools/download.md
- internal/llm/tools/edit.go
- internal/llm/tools/edit.md
- internal/llm/tools/fetch.go
- internal/llm/tools/fetch.md
- internal/llm/tools/glob.go
- internal/llm/tools/glob.md
- internal/llm/tools/grep.go
- internal/llm/tools/grep.md
- internal/llm/tools/ls.go
- internal/llm/tools/ls.md
- internal/llm/tools/multiedit.go
- internal/llm/tools/multiedit.md
- internal/llm/tools/sourcegraph.go
- internal/llm/tools/sourcegraph.md
- internal/llm/tools/view.go
- internal/llm/tools/view.md
- internal/llm/tools/write.go
- internal/llm/tools/write.md
I find it a bit hard to edit/read long chunks of text inside a multi line string.
Also improved the bash description, replacing interpolation with templates. That could be improved a bit further, but already better IMHO.
> refactor: put tool descriptions in markdown files

- internal/llm/agent/agent.go
- internal/tui/components/dialogs/compact/compact.go
- Fixes a critical bug where the session summarization dialog would get stuck in "Generating Summary... Please wait..." state and never close
- Resolves error formatting issues that caused `%!w(<nil>)` display in error messages
When users selected "Summarize Session" from the command menu, the dialog would:
1. Show "Generating Summary... Please wait..." 
2. Never disappear, even when errors occurred
3. Display malformed error messages like `Error: failed to summarize: %!w(<nil>)`
This left users unable to interact with the application and unclear about what went wrong.
Two separate issues were causing this behavior:
1. **Incorrect error variable usage** in `agent.go`: The code was trying to format a `nil` error variable (`err`) instead of the actual response error (`r.Error`)
2. **Missing …
> Fix: Session Summarization Dialog Hanging Indefinitely

- internal/tui/components/chat/splash/splash.go
This commit ensures that the "Yes" and "No" options in the init screen get properly selected when navigating with the keyboard.
Related: https://github.com/charmbracelet/crush/issues/1048
> fix(tui): yes/no init selection

- internal/tui/components/chat/editor/editor.go
- internal/tui/components/chat/editor/keys.go
- internal/tui/components/chat/messages/messages.go
- internal/tui/components/chat/splash/keys.go
- internal/tui/components/completions/keys.go
- internal/tui/components/dialogs/commands/keys.go
- internal/tui/components/dialogs/compact/keys.go
- internal/tui/components/dialogs/filepicker/keys.go
- internal/tui/components/dialogs/keys.go
- internal/tui/components/dialogs/models/keys.go
- internal/tui/components/dialogs/quit/keys.go
- internal/tui/components/dialogs/sessions/keys.go
- internal/tui/page/chat/chat.go
- internal/tui/page/chat/keys.go
adds alt/option+esc binding to current esc key behavior.
This mimics the behavior of Claude Code and allows folks who use Crush from within a terminal emulator that captures the escape key (like Nvim's built in terminal emulator) to use it.
> feat: add alt/option+esc binding to current esc key behavior

- README.md
- go.mod
- go.sum
- internal/cmd/root.go
- internal/config/config.go
- internal/event/all.go
- internal/event/event.go
- internal/event/logger.go
- internal/llm/agent/agent.go
- internal/llm/agent/errors.go
- internal/llm/agent/event.go
- internal/log/log.go
- internal/session/session.go
- internal/tui/components/dialogs/sessions/sessions.go
- internal/tui/tui.go
- main.go
- schema.json
This PR adds pseudonymous usage metrics (tied to a device-specific hash), to inform development and support priorities. The metrics include solely usage metadata; prompts and responses are NEVER collected.
Metrics collection can be opted out by setting the environment variable by setting `export CRUSH_DISABLE_METRICS=1` in your environment, or by setting the following in your config:
```json
{
"options": {
"disable_metrics": true
}
}
```
Crush also respects [`export DO_NOT_TRACK=1`](https://consoledonottrack.com/).
> chore: add metrics and error tracking

- internal/llm/provider/anthropic.go
- internal/llm/provider/gemini.go
- internal/llm/provider/openai.go
- internal/llm/provider/provider.go
If auth failed... its unlikely it'll work next time
Also lowered retries from 8 to 3 - IMHO 8 is too many? It takes a long time and if it didn't work the first couple of times... it's unlikely it'll work in the 8th, IMHO.
closes #741
> fix(provider): do not retry auth errors, lower max tries

- Taskfile.yaml
you can use it as:
```sh
task release -- -m 'some short description'
```
and it'll:
- figure out the next tag using svu
- check if you're on main
- check branch is clean
- drop the nightly tag (it's recreated, so if you have an old one, `git push --tags` will complain about it)
- `git tag --sign <next version>` + any args you pass to release
- `git push --tags`
> chore: add task release

- internal/fsext/fileutil.go
- internal/fsext/fileutil_test.go
The removed line was preventing users from setting directories as root markers, which should be allowed according to the [`Config.LSPConfig.RootMarkers`](https://github.com/charmbracelet/crush/blob/main/internal/config/config.go#L125C87-L125C138) JSON description.
> fix(config): allow directories as root markers

- internal/llm/provider/openai.go
- internal/llm/provider/openai_test.go
- Add better error handling for when OpenAI returns a 429 error with `insufficient_quota` type (indicating the API key has exceeded its usage quota).
- The current retry logic continues indefinitely instead of failing immediately. This causes user prompts to hang without any meaningful feedback.
> fix(openai): 429 insuffice not retry

- main.go
I had to remove this in order diagnose why the application was exiting without warning. Unless there's a good reason to keep this, I suggest we remove it.
Of course, there very well may be a reason to keep it, which is why I'm asking for a review (aside from it being protocol).
> fix: don't suppress application level panics
